services:
  db:
    image: postgres:17
    container_name: boardgame_db
    restart: always
    environment:
      POSTGRES_DB: boardgame_db
      POSTGRES_USER: boardgame_db_user
      POSTGRES_PASSWORD: boardgame_db_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: boardgame_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pg_data:
